### ISSUE TITLE
Maven dependencie

### ISSUE THREAD

**Issue by SinigagliaSteeve** [Haulmont/vaadin-overlays#7]
Hi !
Can you give the dependencie link for maven for your fork please ? :)
Thanks !

**Comment by jreznot** [comment]
Sorry, there is no Maven repository. Only binaries are available in Github releases: https://github.com/Haulmont/vaadin-overlays/releases

**Comment by SinigagliaSteeve** [comment]
Okay thanks, maybe in futur release ?
I don't have all information but why this choice ? The project was very good and usefull

**Comment by jreznot** [comment]
I'm not an original author of this addon. This project is just legacy port to Vaadin 7.6 for legacy projects that need it. Currently it does not support scrolling of content and uses additional top level overlay.

It can be easily replaced with CssLayout with "position: relative" and "position: absolute" for overlay content, so we don't promote it and recommend to get rid of it.
